/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "includes.h" //teng
#include "app.h" //teng
#include "EmWinHZFont.h"//teng
#include "ff.h"//teng
#include "malloc.h"//teng
#include "exfuns.h"//teng
//#include "treenleafimage.h"//teng
extern u8*const FILE_TYPE_TBL[7][13];
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x06)
//#define ID_MENU_0     (GUI_ID_USER + 0x07)
#define ID_EDIT_0     (GUI_ID_USER + 0x08)
#define ID_TEXT_0     (GUI_ID_USER + 0x09)
#define ID_TREEVIEW_0 (GUI_ID_USER + 0x0A)
//#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
//#define ID_TEXT_2     (GUI_ID_USER + 0x0C)



#define ID_FRAMEWIN_1     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_1     (GUI_ID_USER + 0x02)
#define ID_BUTTON_2     (GUI_ID_USER + 0x03)
#define ID_BUTTON_3     (GUI_ID_USER + 0x04)
#define ID_TEXT_1     (GUI_ID_USER + 0x05)

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "图片浏览", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x00, 0 },
  { BUTTON_CreateIndirect, "上一张", ID_BUTTON_0, 3, 270, 50, 20, 0, 0x00, 0 },
  { BUTTON_CreateIndirect, "缩小", ID_BUTTON_1, 62, 270, 50, 20, 0, 0x00, 0 },
  { BUTTON_CreateIndirect, "放大", ID_BUTTON_2, 120, 270, 50, 20, 0, 0x00, 0 },
  { BUTTON_CreateIndirect, "下一张", ID_BUTTON_3, 177, 270, 50, 20, 0, 0x00, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

TREEVIEW_ITEM_Handle   hTreeItemSel;
TREEVIEW_ITEM_Handle   hTreeItemInc;
TREEVIEW_ITEM_Handle   hTreeItemDec;
WM_HWIN hWinx;
WM_HWIN hItemTree;
u8 pathbuffx[150]={0};
TREEVIEW_Handle treeitem;
WM_HWIN himage;

extern u8 gifstop;

//根据文件类型显示不同类型的图片
void ShowPicture(u8 *path, int member, int denom, u8 dirx)
{
	int res;
	u8 pathbuffn[150]={0};
	strcpy((char *)pathbuffn, (char *)path);
	if(f_typetell(pathbuffn) != 0xFF) {
		WM_SelectWindow(himage);
		GUI_SetBkColor(GUI_GRAY);
		GUI_Clear();
		if(f_typetell(pathbuffn)==T_BMP) {
			res = dispbmp(path,1,0,0, member, denom);
			if(res != 0)
				dispbmpex(path,1,0,0, member, denom);
		} else if( (f_typetell(pathbuffn)==T_JPG) || (f_typetell(pathbuffn)==T_JPEG) ) {
			res = displayjpeg(path,1,0,0, member, denom);
			if(res != 0)
				displayjpegex(path,1,0,0, member, denom);
		} else if(f_typetell(pathbuffn)==T_PNG) {
			res = displaypng(path,1,0,0, member, denom);
			if(res != 0)
				displaypngex(path,1,0,0, member, denom);
		} else if(f_typetell(pathbuffn)==T_GIF) {
			gifstop = 0;//teng
			res = displaygif(path,1,0,0, member, denom);
			if(res != 0)
				displaygifex(path,1,0,0, member, denom);
		}
	} else if(dirx == 0) {
		TREEVIEW_IncSel(treeitem);
	} else if(dirx == 1) {
		TREEVIEW_DecSel(treeitem);
	}
}


//dir0 dec   1 inc  其它不变
TREEVIEW_ITEM_Handle IncDecPathx(WM_MESSAGE *pMsg, U16 TREEVIEW_IDx, TREEVIEW_ITEM_Handle hTreeItemSelx, u8 dir)
{
	u8 pbuff[150]={0};
	u8 pbufft[150]={0};
	u8 pathbuff[150]={0};
	u8 pathbufftemp[150]={0};
	TREEVIEW_ITEM_INFO ItemInfo;
	u8 treelevel,i;
	WM_HWIN _hMenu;
	WM_HWIN hItem;

	TREEVIEW_ITEM_Handle   hTreeItemCur;  
	TREEVIEW_ITEM_Handle   hTreeItemNew;
//	TREEVIEW_ITEM_Handle   hTreeItemSel;

	hItem = WM_GetDialogItem(hWinx, TREEVIEW_IDx);                             		//获取句柄
	if(dir == 0)//dec
	{
		TREEVIEW_DecSel(treeitem);
	}else if(dir == 1)//inc
	{
		TREEVIEW_IncSel(treeitem);
	}
	hTreeItemCur = TREEVIEW_GetSel(hItem);                                          //获取选中条目
	hTreeItemSel = hTreeItemCur;
	TREEVIEW_ITEM_GetInfo(hTreeItemCur,&ItemInfo);                                  //获取选中条目信息
	treelevel = ItemInfo.Level;                                                     //复制缩进深度
	TREEVIEW_ITEM_GetText(hTreeItemCur,pbuff,50);                                   //获取选中条目名称
	for(i=0;i<treelevel;i++) {
		hTreeItemNew = TREEVIEW_GetItem(hItem,hTreeItemCur,TREEVIEW_GET_PARENT);    //获取上级对象
		TREEVIEW_ITEM_GetText(hTreeItemNew,pbufft,50);                              //获取上级对象名称
		sprintf((char *)pathbuff,"%s/%s",pbufft,pbuff);                                     //格式化文本
		sprintf((char *)pbuff,"%s",pathbuff);                                               //复制
		hTreeItemCur = hTreeItemNew;                                                //对换、更新句柄
	}
	//以下为判断盘符并替路径名称
	i = filePathCheck(pathbuff);                                                    //判断盘符
	if(i != 0xFF) {
		if(i == 0) {                                                                  //修改路径为x:/xxxx/xxx/xx.xxx格式
            //SDCard
			strcpy((char *)pathbufftemp,(char *)pathbuff);
			pathbufftemp[0] = '0';
			pathbufftemp[1] = ':';
			for(i=0;i<strlen((char *)pathbuff);i++) {
				pathbufftemp[i+2] = pathbuff[i+6];
			}
		} else if(i == 1) {
            //ExFlash
			strcpy((char *)pathbufftemp,(char *)pathbuff);
			pathbufftemp[0] = '1';
			pathbufftemp[1] = ':';
			for(i=0;i<strlen((char *)pathbuff);i++) {
				pathbufftemp[i+2] = pathbuff[i+7];
			}
		}
	}
	strcpy((char *)pathbuff,(char *)pathbufftemp);
	hItem = WM_GetDialogItem(pMsg->hWin, ID_FRAMEWIN_0);                                //获取句柄
	FRAMEWIN_SetText(hItem,(char *)pathbuff);                                                  //显示路径
	strcpy((char *)pathbuffx,(char *)pathbuff);
	return hTreeItemSel;
}



int memberx=10, denomx=10;
//WM_HWIN himage;
static void _cbDialog(WM_MESSAGE * pMsg) {
    WM_HWIN hItem;
	int NCode;
	int Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
    case WM_DELETE:
        gifstop = 1;//teng
        WM_DefaultProc(pMsg);
        break;
	case WM_INIT_DIALOG:
	//
	// Initialization of 'Framewin'
	//
	memberx=10, denomx=10;     //恢复1:1显示
	hItem = pMsg->hWin;
	FRAMEWIN_SetTitleHeight(hItem, 20);
//	FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
	FRAMEWIN_SetFont(hItem,&GUI_FontHZ16);
	FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
	FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
	himage = WM_CreateWindowAsChild(5,23,230,265,hItem,WM_CF_SHOW|WM_CF_STAYONTOP,NULL,0);
//	WM_SelectWindow(himage);
//	GUI_SetBkColor(GUI_LIGHTGRAY);
//	GUI_Clear();
    
    //设置按钮文字
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, &GUI_FontHZ12);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, &GUI_FontHZ12);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, &GUI_FontHZ12);
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, &GUI_FontHZ12);

	IncDecPathx(pMsg, ID_TREEVIEW_0, treeitem, 2);
//	WM_SelectWindow(himage);
//	GUI_SetBkColor(GUI_DARKGRAY);
//	GUI_Clear();
	FRAMEWIN_SetText(pMsg->hWin, (char *)pathbuffx);
	ShowPicture(pathbuffx, memberx, denomx, 2);
	// USER START (Optionally insert additional code for further widget initialization)
	// USER END
	break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by '<<'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		gifstop = 1;//teng
		  IncDecPathx(pMsg, ID_TREEVIEW_0, treeitem, 0);
		  
//		  WM_SelectWindow(himage);
//		  GUI_SetBkColor(GUI_LIGHTGRAY);
//		  GUI_Clear();
		  FRAMEWIN_SetText(pMsg->hWin, (char *)pathbuffx);
		  ShowPicture(pathbuffx, memberx, denomx, 0);
//		  displayjpegex(pathbuffx,1,0,0,memberx,denomx);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by '--'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  gifstop = 1;//teng
	  memberx--;
	  denomx++;
	  if(memberx==0)
	  {
		  memberx = 1;
		  denomx++;
	  }
	    IncDecPathx(pMsg, ID_TREEVIEW_0, treeitem, 2);

//		WM_SelectWindow(himage);
//		GUI_SetBkColor(GUI_LIGHTGRAY);
//		GUI_Clear();
		FRAMEWIN_SetText(pMsg->hWin, (char *)pathbuffx);
	    ShowPicture(pathbuffx, memberx, denomx, 2);
//		displayjpegex(pathbuffx,1,0,0,memberx,denomx);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by '++'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
	  gifstop = 1;//teng
	  memberx++;
	  denomx--;
	  if(denomx==0)
	  {
		  denomx = 1;
		  memberx--;
	  }
		IncDecPathx(pMsg, ID_TREEVIEW_0, treeitem, 2);

//		WM_SelectWindow(himage);
//		GUI_SetBkColor(GUI_LIGHTGRAY);
//		GUI_Clear();
		FRAMEWIN_SetText(pMsg->hWin, (char *)pathbuffx);
	    ShowPicture(pathbuffx, memberx, denomx, 2);
//		displayjpegex(pathbuffx,1,0,0,memberx,denomx);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by '>>'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		gifstop = 1;//teng
		  IncDecPathx(pMsg, ID_TREEVIEW_0, treeitem, 1);
		  
//		  WM_SelectWindow(himage);
//		  GUI_SetBkColor(GUI_LIGHTGRAY);
//		  GUI_Clear();
		  FRAMEWIN_SetText(pMsg->hWin, (char *)pathbuffx);
	      ShowPicture(pathbuffx, memberx, denomx, 1);
//		  displayjpegex(pathbuffx,1,0,0,memberx,denomx);
//	  WM_SelectWindow(himage);
//	  GUI_SetBkColor(GUI_LIGHTGRAY);
//	  GUI_Clear();
//	  FRAMEWIN_SetText(pMsg->hWin,"0:/PICTURE/dog.jpg");
//	  displayjpegex(pathbuffx,1,0,0,memberx,denomx);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
WM_HWIN CreateFramewin(WM_MESSAGE * pMsg) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, pMsg->hWin, 0, 0);
	return hWin;
}








// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreatex[] = {
	{ FRAMEWIN_CreateIndirect, "图片浏览器", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x00, 0 },
	{ EDIT_CreateIndirect, "Edit", ID_EDIT_0, 35, 2, 195, 18, 0, 0x64, 0 },
	{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 1, 4, 35, 14, 0, 0x64, 0 },
	{ TREEVIEW_CreateIndirect, "Treeview", ID_TREEVIEW_0, 0, 21, 230, 271, 0, 0x00, 0 },
//	{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 1, 262, 100, 14, 0, 0x64, 0 },
//	{ TEXT_CreateIndirect, "Text", ID_TEXT_2, 110, 262, 100, 14, 0, 0x64, 0 },
	// USER START (Optionally insert additional widgets)
	// USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

//树形文件初始化
WM_HWIN TREEViewInitx(WM_MESSAGE * pMsg,U16 ID)
{
	WM_HWIN hItem;
	TREEVIEW_ITEM_Handle hTreeItemCur;  
	TREEVIEW_ITEM_Handle hTreeItemNew;
	hItem = WM_GetDialogItem(pMsg->hWin, ID);
treeitem = hItem;
	TREEVIEW_SetAutoScrollH(hItem,1);
	TREEVIEW_SetAutoScrollV(hItem,1);
	TREEVIEW_SetFont(hItem,&GUI_FontHZ16);
	TREEVIEW_SetSelMode(hItem, TREEVIEW_SELMODE_ROW);                                //整行选中模式

	hTreeItemCur = TREEVIEW_GetItem(hItem, 0, TREEVIEW_GET_LAST);
	hTreeItemNew = TREEVIEW_ITEM_Create(TREEVIEW_ITEM_TYPE_NODE, "ExFlash", 0);      //外部ExFlash
//	Fill_FileList("1:",hItem,hTreeItemNew,NULL);
	TREEVIEW_AttachItem(hItem, hTreeItemNew, hTreeItemCur, TREEVIEW_INSERT_BELOW);   //增加到树形图

	hTreeItemCur = TREEVIEW_GetItem(hItem, 0, TREEVIEW_GET_LAST);
	hTreeItemNew = TREEVIEW_ITEM_Create(TREEVIEW_ITEM_TYPE_NODE, "SDCard", 0);       //SDCard
	Fill_FileList("0:",hItem,hTreeItemNew,NULL,0x50);                                    //扫描SDCard文件
	TREEVIEW_AttachItem(hItem, hTreeItemNew, hTreeItemCur, TREEVIEW_INSERT_BELOW);   //增加到树形图

	hTreeItemCur = TREEVIEW_GetItem(hItem, 0, TREEVIEW_GET_FIRST);
	Fill_FileList("1:",hItem,hTreeItemCur,NULL,0x50);                                    //扫描ExFlash文件
	TREEVIEW_AttachItem(hItem, hTreeItemNew, hTreeItemCur, TREEVIEW_INSERT_BELOW);   //增加到树形图
	return hItem;
}

//u8 pathbuffx[150]={0};
//树形文件路径显示，并返回盘符名称句柄
TREEVIEW_ITEM_Handle TREEVIEWShowPathx(WM_MESSAGE *pMsg, U16 TREEVIEW_IDx, U16 EDIT_IDx)
{
	u8 pbuff[150]={0};
	u8 pbufft[150]={0};
	u8 pathbuff[150]={0};
	u8 pathbufftemp[150]={0};
	TREEVIEW_ITEM_INFO ItemInfo;
	u8 treelevel,i;
	WM_HWIN _hMenu;
	WM_HWIN hItem;

	TREEVIEW_ITEM_Handle   hTreeItemCur;  
	TREEVIEW_ITEM_Handle   hTreeItemNew;
//	TREEVIEW_ITEM_Handle   hTreeItemSel;

	hItem = WM_GetDialogItem(pMsg->hWin, TREEVIEW_IDx);                             //获取句柄
	hTreeItemCur = TREEVIEW_GetSel(hItem);                                          //获取选中条目
	hTreeItemSel = hTreeItemCur;
	TREEVIEW_ITEM_GetInfo(hTreeItemCur,&ItemInfo);                                  //获取选中条目信息
	treelevel = ItemInfo.Level;                                                     //复制缩进深度
	TREEVIEW_ITEM_GetText(hTreeItemCur,pbuff,50);                                   //获取选中条目名称
	for(i=0;i<treelevel;i++)
	{
		hTreeItemNew = TREEVIEW_GetItem(hItem,hTreeItemCur,TREEVIEW_GET_PARENT);    //获取上级对象
		TREEVIEW_ITEM_GetText(hTreeItemNew,pbufft,50);                              //获取上级对象名称
		sprintf((char *)pathbuff,"%s/%s",pbufft,pbuff);                                     //格式化文本
		sprintf((char *)pbuff,"%s",pathbuff);                                               //复制
		hTreeItemCur = hTreeItemNew;                                                //对换、更新句柄
	}
	//以下为判断盘符并替路径名称
	i = filePathCheck(pathbuff);                                                    //判断盘符
	if(i != 0xFF)
	{
		if(i == 0)                                                                  //修改路径为x:/xxxx/xxx/xx.xxx格式
		{                                                                           //SDCard
			strcpy((char *)pathbufftemp,(char *)pathbuff);
			pathbufftemp[0] = '0';
			pathbufftemp[1] = ':';
			for(i=0;i<strlen((char *)pathbuff);i++)
			{
				pathbufftemp[i+2] = pathbuff[i+6];
			}
		}
		else if(i == 1)
		{                                                                           //ExFlash
			strcpy((char *)pathbufftemp,(char *)pathbuff);
			pathbufftemp[0] = '1';
			pathbufftemp[1] = ':';
			for(i=0;i<strlen((char *)pathbuff);i++)
			{
				pathbufftemp[i+2] = pathbuff[i+7];
			}
		}
	}
	strcpy((char *)pathbuff,(char *)pathbufftemp);
    hItem = WM_GetDialogItem(pMsg->hWin, EDIT_IDx);                                //获取路径EDIT句柄
	EDIT_SetText(hItem,(char *)pathbuff);                                                  //显示路径
	strcpy((char *)pathbuffx,(char *)pathbuff);
TREEVIEW_SetSel(treeitem, hTreeItemSel);    //设置回点击item
//TREEVIEW_IncSel(treeitem);                //测试用
//TREEVIEWShowPathx(pMsg,ID_TREEVIEW_0,ID_EDIT_0);   //测试用
	return hTreeItemSel;
}


u8 filesameflag=0;
u8 pbuffx[50]={0};
//TREEVIEW_ITEM_Handle   hTreeItemSel;
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialogx(WM_MESSAGE * pMsg) {
	
	u8 pbuff[50]={0};
	u8 pbufft[50]={0};
//	u8 pathbuff[100]={0};
//	u8 pathbufftemp[100]={0};
//	TREEVIEW_ITEM_INFO ItemInfo;
//	u8 treelevel,i;

	TREEVIEW_ITEM_Handle   hTreeItemLast;
//	TREEVIEW_ITEM_Handle   hTreeItemCur;  
//	TREEVIEW_ITEM_Handle   hTreeItemNew;
		
//	MENU_ITEM_DATA         ItemData;
	WM_HWIN                hItem;
	int                    NCode;
	int                    Id;
	// USER START (Optionally insert additional variables)
	// USER END
	switch (pMsg->MsgId) {
		case WM_INIT_DIALOG:
			//
			// Initialization of 'Browser'
			//
			hItem = pMsg->hWin;
			FRAMEWIN_SetTextColor(hItem,GUI_DARKGRAY);
			FRAMEWIN_SetTitleHeight(hItem, 20);
			FRAMEWIN_SetFont(hItem, &GUI_FontHZ16);
			FRAMEWIN_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			FRAMEWIN_AddCloseButton(hItem,FRAMEWIN_BUTTON_RIGHT,0);
			//
			// Initialization of 'Edit'
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
			EDIT_SetText(hItem, "");
			EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			EDIT_SetFont(hItem, &GUI_FontHZ12);
		//	WM_DisableWindow(hItem);           //禁用状态
			//
			// Initialization of 'Text'
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
			TEXT_SetText(hItem, "路径:");
			TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
			TEXT_SetFont(hItem, &GUI_FontHZ12);
			//
			// Initialization of 'Treeview'
			//
			hItem = TREEViewInitx(pMsg,ID_TREEVIEW_0); //树形文件初始化
			// USER END
		break;
		
		case WM_NOTIFY_PARENT:
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch(Id) {
				case ID_EDIT_0: // Notifications sent by 'Edit'
					switch(NCode) {
						case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
						case WM_NOTIFICATION_RELEASED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
						case WM_NOTIFICATION_VALUE_CHANGED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
						// USER START (Optionally insert additional code for further notification handling)
						// USER END
					}
				break;
				case ID_TREEVIEW_0: // Notifications sent by 'Treeview'
					switch(NCode) {
						case WM_NOTIFICATION_CLICKED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
						case WM_NOTIFICATION_RELEASED:
						// USER START (Optionally insert code for reacting on notification message)

							hTreeItemSel = TREEVIEWShowPathx(pMsg,ID_TREEVIEW_0,ID_EDIT_0);					//根据选中条目显示路径

							hItem = WM_GetDialogItem(pMsg->hWin, ID_TREEVIEW_0);                            //获取树形句柄
							TREEVIEW_ITEM_GetText(hTreeItemSel,pbufft,50);                                 //获取选中文本
							if( (f_typetell(pbufft)>>4) == (0x50>>4) )
							{
								if(strcmp((char *)pbuffx,(char *)pbufft)==0)
								{
									filesameflag = 1;
								}
								else
								{
									strcpy((char *)pbuffx,(char *)pbufft);
									filesameflag = 0;
								}
								if(filesameflag==1)  //第二次单击则打开文件
								{
									CreateFramewin(pMsg);     //图片显示窗口
								}
							}
							
						// USER END
						break;
						case WM_NOTIFICATION_MOVED_OUT:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
						case WM_NOTIFICATION_SEL_CHANGED:
						// USER START (Optionally insert code for reacting on notification message)
						// USER END
						break;
						// USER START (Optionally insert additional code for further notification handling)
						// USER END
					}
				break;
				// USER START (Optionally insert additional code for further Ids)
				// USER END
				default:
					WM_DefaultProc(pMsg);
			}
		break;
		// USER START (Optionally insert additional message handling)
		// USER END
		default:
			WM_DefaultProc(pMsg);
		break;
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateBrowser
*/
WM_HWIN CreatePicture(void);
WM_HWIN CreatePicture(void) {
	WM_HWIN hWin;

	hWin = GUI_CreateDialogBox(_aDialogCreatex, GUI_COUNTOF(_aDialogCreatex), _cbDialogx, WM_HBKWIN, 0, 0);
	hWinx = hWin;
    return hWin;
//	while(OnICON1)
//	{
//		GUI_Delay(20);
//	}
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
