/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "EmWinHZFont.h"//teng
#include "LISTBOX.h"//teng
#include "MessageBoxUser.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0        (GUI_ID_USER + 0x00)
#define ID_LISTBOX_0        (GUI_ID_USER + 0x01)
#define ID_SWIPELIST_0        (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// 设置选项
//#define SECTION_TITLE 11
//const unsigned char *section_title[SECTION_TITLE][2]=
//{
//    {"", ">> 系统设置"},// 这种是分隔栏
//    {"日期与时间", "设置当前系统日期与时间"},
//    {"主题色", "设置桌面主题色"},
//    {"关于", ""},// 这种是只有标题，没有小字
//    {"", ">> 测试标题"},
//    {"测试文本1", "小标题文字哈哈1"},
//    {"测试文本2", "小标题文字哈哈2"},
//    {"测试文本3", "小标题文字哈哈3"},
//    {"测试文本4", "小标题文字哈哈4"},
//    {"测试文本5", "小标题文字哈哈5"},
//    {"测试", ""},
//};
const unsigned char *section_title[15]=
{
    {"1.日期与时间"},
    {"2.设置桌面主题色"},
    {"3.关于"},
    {"4.刷屏速度"},
    {"5.计算分形图Julia"},
    {"6.测试文本2"},
    {"7.测试文本3"},
    {"8.测试文本4"},
    {"9.测试文本5"},
    {"10.测试1"},
    {"11.测试2"},
    {"12.测试3"},
    {"13.测试4"},
    {"14.测试5"},
    {"15.测试6"},
};
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "设置", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { LISTBOX_CreateIndirect, "LISTBOX", ID_LISTBOX_0, 0, 0, 230, 293, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/


void startFramewinByIndex(int index) {
    unsigned char pbuff[20]={0};
    switch (index) {
        case 0:
            CreateSetDateTime();
            break;
        case 3:
            GUIDEMO_Speed();
            break;
        case 4:
            CreateJulia();
        break;
        default:
            sprintf(pbuff,"行号:%d", index);
//            MESSAGEBOX_Create(pbuff, "Message", GUI_MESSAGEBOX_CF_MODAL);
            MESSAGEBOX_Create_User_Modal(pbuff, "提示");
            break;
    }
}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
//#define ITEM_HEIGHT 40
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  WM_HWIN hItemx;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  int sel;
  int i;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
    LISTBOX_SetFont(hItem, &GUI_FontHZ16);
    LISTBOX_SetItemSpacing(hItem, 7);
    LISTBOX_SetTextAlign(hItem, GUI_TA_VCENTER);
    LISTBOX_SetAutoScrollV(hItem, 1);
    hItemx = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItemx, 20);
//	FRAMEWIN_SetTextColor(hItemx,GUI_DARKGRAY);
	FRAMEWIN_SetFont(hItemx,&GUI_FontHZ16);
	FRAMEWIN_SetTextAlign(hItemx, GUI_TA_LEFT | GUI_TA_VCENTER);
	FRAMEWIN_AddCloseButton(hItemx,FRAMEWIN_BUTTON_RIGHT,0);
      
    for (i=0;i<15;i++) {
        LISTBOX_AddString(hItem, section_title[i]);
    }
    
//    for (i=0;i<SECTION_TITLE;i++) {
//        if (strlen(section_title[i][0]) == 0) {
//            SWIPELIST_AddSepItem(hItem, section_title[i][1], 30);
//            continue;
//        }
//        SWIPELIST_AddItem(hItem, section_title[i][0], ITEM_HEIGHT);
////        SWIPELIST_SetBitmap(hItem, i, 0, &_bmmusic);// #include "treenleafimage.h"
//        if (strlen(section_title[i][1]) > 0) {
//            SWIPELIST_AddItemText(hItem, i, section_title[i][1]);
//        }
//    }
//    WM_MOTION_SetMoveable(hItem, WM_CF_MOTION_Y, 1);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_LISTBOX_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTBOX_0);
        sel = LISTBOX_GetSel(hItem);
//        sel = SWIPELIST_GetReleasedItem(hItem);
        startFramewinByIndex(sel);
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateSetting(void);
WM_HWIN CreateSetting(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
